spring:
  datasource:
#    url: jdbc:mysql://151.80.70.40:3306/goclean_db
#    username: dima
#    password: pJ@ka6P45
    url: jdbc:mysql://localhost:3306/goclean_db
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000

UserController:
  signin: Authenticates user and returns its JWT token
  signup: Creates user and returns it and its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  all: Returns list of all users
  forgotPassword: Generate the password-reset token, send it to the user's e-mail and write to the database
  checkResetToken: Check the validity of the password-reset token
  refreshPassword: Updates the user password
ServiceController:
  all: Returns list of all services
  add: Adds service
  delete: Deletes specific service by its id
  get: Returns specific service by its id and name
  edit: Edits specific service by its id and entity
DistrictController:
  all: Returns districts' list
  add: Adds district
  delete: Deletes district by id
  get: Get specific district by its id and name
  edit: Edits specific district by its id and entity

